export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';


export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_REGISTER_LOADING = 'USER_REGISTER_LOADING';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING';
export const USER_LOGIN_RESET_STATE = 'USER_LOGIN_RESET_STATE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CATEGORY_LOAD_SUCCESS = 'CATEGORY_LOAD_SUCCESS';
export const CATEGORY_LOAD_ERROR = 'CATEGORY_LOAD_ERROR';

export const MOVIE_LOAD = "MOVIE_LOAD";
export const MOVIE_LOAD_SUCCESS = "MOVIE_LOAD_SUCCESS";
export const MOVIE_LOAD_ERROR = "MOVIE_LOAD_ERROR";